param (
    [string]$projectName
)

if (-not $projectName) {
    Write-Error "Error: A project name is required as an argument."
    exit 1
}

# Create the Rust project
cargo new $projectName

# Change to the project directory
Set-Location $projectName

# Create the .gitignore file with the specified content
@"
# Generated by Cargo
# will have compiled files and executables
debug/
target/

# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk

# MSVC Windows builds of rustc generate these, which store debugging information
*.pdb
"@ | Out-File -FilePath .gitignore -Encoding utf8

Write-Output "Project '$projectName' successfully created with .gitignore."
